# Generated by Django 4.2.1 on 2025-04-10 09:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuyerIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('descp', models.TextField(null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='location/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PropertySubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Estateapp.propertycategory')),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200, null=True)),
                ('Address_line1', models.CharField(max_length=200, null=True)),
                ('City', models.CharField(max_length=200, null=True)),
                ('State', models.CharField(max_length=200, null=True)),
                ('Zipcode', models.CharField(max_length=6, null=True)),
                ('Brochure', models.FileField(blank=True, null=True, upload_to='brochure/')),
                ('video_link', models.URLField(null=True)),
                ('Price', models.CharField(max_length=200, null=True)),
                ('Price_Words', models.CharField(max_length=800, null=True)),
                ('Built_up_Area', models.CharField(max_length=200, null=True)),
                ('Total_Area', models.CharField(max_length=200, null=True)),
                ('Possesion_Time', models.CharField(max_length=200, null=True)),
                ('Unit_Variants', models.CharField(max_length=200, null=True)),
                ('RERA_No', models.CharField(max_length=200, null=True)),
                ('Amenities', models.CharField(max_length=200, null=True)),
                ('Abt_builder', models.TextField(null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('project_slug', autoslug.fields.AutoSlugField(editable=False, populate_from='Title', unique=True)),
                ('Project_Location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Estateapp.location')),
                ('buyer_intent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estateapp.buyerintent')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estateapp.propertycategory')),
                ('stage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estateapp.projectstage')),
                ('subcategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estateapp.propertysubcategory')),
            ],
        ),
    ]
