# Generated by Django 4.2.1 on 2025-04-16 11:53

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0003_alter_projects_project_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Built_up_Area',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Price_Words',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='State',
        ),
        migrations.AddField(
            model_name='projects',
            name='About_Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Bann1',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Bann2',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Bann3',
            field=models.ImageField(blank=True, null=True, upload_to='banner/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Configuration',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Featur_Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Gallery',
            field=models.ImageField(blank=True, null=True, upload_to='gallery/'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Highlights',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Location_Content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Map_Link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Mobile',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Size',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='Whatsapp_no',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Possesion_Time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Total_Area',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Unit_Variants',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
