# Generated by Django 4.2.1 on 2025-04-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0004_remove_projects_built_up_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='amenities/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Amenities',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='Configuration',
        ),
        migrations.AddField(
            model_name='projects',
            name='Amenities',
            field=models.ManyToManyField(blank=True, to='Estateapp.amenity'),
        ),
        migrations.AddField(
            model_name='projects',
            name='Configuration',
            field=models.ManyToManyField(blank=True, to='Estateapp.configuration'),
        ),
    ]
