# Generated by Django 4.2.1 on 2025-04-16 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0005_amenity_configuration_remove_projects_amenities_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Floor_Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
            ],
        ),
        migrations.AddField(
            model_name='configuration',
            name='pricing',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='configuration',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='projects',
            name='floor_plans',
            field=models.ManyToManyField(blank=True, related_name='projects', to='Estateapp.floor_plan'),
        ),
    ]
