# Generated by Django 4.2.1 on 2025-04-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0006_floor_plan_configuration_pricing_configuration_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='Gallery',
        ),
        migrations.CreateModel(
            name='ProjectGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='Estateapp.projects')),
            ],
        ),
    ]
