# Generated by Django 4.2.1 on 2025-04-18 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0007_remove_projects_gallery_projectgalleryimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configuration',
            old_name='name',
            new_name='c_name',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='pricing',
            new_name='c_pricing',
        ),
        migrations.RenameField(
            model_name='configuration',
            old_name='size',
            new_name='c_size',
        ),
    ]
