# Generated by Django 4.2.1 on 2025-04-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0008_rename_name_configuration_c_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Highlights',
            field=models.TextField(blank=True, help_text='Enter each highlight on a new line (no bullets or HTML needed).', null=True),
        ),
    ]
