# Generated by Django 4.2.1 on 2025-04-21 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0009_alter_projects_highlights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Location_Content',
            field=models.TextField(blank=True, help_text='Enter each Location highlight on a new line (no bullets or HTML needed).', null=True),
        ),
    ]
