# Generated by Django 4.2.1 on 2025-04-24 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0011_project_enquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='Bann1',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Bann2',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='Bann3',
            field=models.ImageField(null=True, upload_to='banner/'),
        ),
    ]
