# Generated by Django 4.2.1 on 2025-04-30 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0012_alter_projects_bann1_alter_projects_bann2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='gtm_id',
            field=models.CharField(blank=True, help_text='Add GTM ID like GTM-XXXXXX for this specific project', max_length=50, null=True),
        ),
    ]
