# Generated by Django 4.2.1 on 2025-05-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0014_city_alter_projects_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='old_city',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
