# Generated by Django 4.2.1 on 2025-05-01 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0015_projects_old_city'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='City',
            new_name='Cities',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='old_city',
        ),
        migrations.AddField(
            model_name='projects',
            name='New_City',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Estateapp.cities'),
        ),
        migrations.AlterField(
            model_name='projects',
            name='City',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
