# Generated by Django 4.2.1 on 2025-05-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0016_rename_city_cities_remove_projects_old_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='New_City',
        ),
        migrations.DeleteModel(
            name='Cities',
        ),
    ]
