# Generated by Django 4.2.1 on 2025-05-01 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0017_remove_projects_new_city_delete_cities'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_seher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='seher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Estateapp.city_seher'),
        ),
    ]
