# Generated by Django 4.2.1 on 2025-05-01 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0018_city_seher_projects_seher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='seher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Estateapp.city_seher'),
        ),
    ]
