# Generated by Django 4.2.1 on 2025-05-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0019_alter_projects_seher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='City',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
