# Generated by Django 4.2.1 on 2025-05-01 12:38

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0020_alter_projects_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_seher',
            name='city_slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='name', unique=True),
        ),
        migrations.AddField(
            model_name='city_seher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='City_seher/'),
        ),
    ]
