# Generated by Django 4.2.1 on 2025-05-01 12:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0021_city_seher_city_slug_city_seher_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_seher',
            name='city_slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique=True),
        ),
    ]
