# Generated by Django 4.2.1 on 2025-05-01 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0022_alter_city_seher_city_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_seher',
            name='city_slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city_seher',
            name='name',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
