# Generated by Django 4.2.1 on 2025-05-01 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0023_alter_city_seher_city_slug_alter_city_seher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city_seher',
            name='city_slug',
        ),
        migrations.RemoveField(
            model_name='city_seher',
            name='image',
        ),
    ]
