# Generated by Django 4.2.1 on 2025-05-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0024_remove_city_seher_city_slug_remove_city_seher_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projects',
            name='seher',
        ),
        migrations.AddField(
            model_name='city_seher',
            name='city_slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='city_seher',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='City',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Estateapp.city_seher'),
        ),
    ]
