# Generated by Django 4.2.1 on 2025-05-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0026_alter_city_seher_city_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_seher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='city/'),
        ),
    ]
