# Generated by Django 4.2.1 on 2025-05-09 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0028_blogs_contact_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Proj_Logo',
            field=models.ImageField(blank=True, null=True, upload_to='logo/'),
        ),
    ]
