# Generated by Django 4.2.1 on 2025-07-31 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0030_location_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='city_seher',
            name='descp',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='city_seher',
            name='title',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='city_seher',
            name='why_invest',
            field=models.TextField(null=True),
        ),
    ]
