# Generated by Django 4.2.1 on 2025-07-31 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0031_property_brand_city_seher_descp_city_seher_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='city_seher',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='city/'),
        ),
    ]
