# Generated by Django 4.2.1 on 2025-07-31 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0032_city_seher_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city_seher',
            name='image',
            field=models.ImageField(null=True, upload_to='city/'),
        ),
        migrations.AlterField(
            model_name='city_seher',
            name='image2',
            field=models.ImageField(null=True, upload_to='city/'),
        ),
    ]
