# Generated by Django 4.2.1 on 2025-08-05 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Estateapp', '0033_alter_city_seher_image_alter_city_seher_image2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project_Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=400, null=True)),
                ('logo', models.ImageField(null=True, upload_to='logos/')),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='projectbrand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Brands', to='Estateapp.project_brand'),
        ),
    ]
